[server_cfg]
host = "127.0.0.1"
port = 28082

[delivery_cfg]
ack_mode = "delivered"
dump_directory = "./data/relay-demo/monitoring/queue"

[logs_cfg]
output = "stderr"

[destinations_cfg]
stdout = false

[destinations_cfg.file]
enabled = true
directory = "./data/relay-demo/monitoring/packets"
