package logger

var (
	EVENT_STARTUP          = "startup"
	EVENT_SHUTDOWN         = "shutdown"
	EVENT_RECIEVED_AUTH    = "auth_recieved"
	EVENT_AUTH_REQUESTED   = "auth_requested"
	EVENT_AUTH_SUCCESS     = "auth_success"
	EVENT_AUTH_REJECTED    = "auth_rejected"
	EVENT_CONFIG_ERROR     = "configuration_error"
	EVENT_LOGGER_ERROR     = "logger_error"
	EVENT_PACKET_RECEIVED  = "packet_received"
	SCOPE_CONFIG           = "configuration"
	SCOPE_STARTUP          = "startup"
	SCOPE_SHUTDOWN         = "shutdown"
	SCOPE_LOGGER           = "logger"
	SCOPE_PACKETS          = "packets"
	SCOPE_SERVER           = "server"
	SCOPE_DELIVERY         = "delivery"
	EVENT_LISTENING        = "listening"
	EVENT_CONNECTION_ERROR = "connection_error"
	EVENT_PACKET_REJECTED  = "packet_rejected"
	EVENT_DELIVERY_ERROR   = "delivery_error"
	EVENT_DUMP_SAVED       = "dump_saved"
	EVENT_SERVER_ERROR     = "server_error"
)
